from datetime import datetime
from zoneinfo import ZoneInfo

MX_TIMEZONE = ZoneInfo("America/Monterrey")


MOCK_GRAPH_INPUT = {
    "case_id": "CASE_001",
    "target_entity_id": "A",
    "entities": [
        {
            "entity_id": "A",
            "name": "Empresa Atlas",
            "entity_type": "company",
            "rfc": "AAA010101AAA",
        },
        {
            "entity_id": "B",
            "name": "Empresa Boreal",
            "entity_type": "company",
            "rfc": "BBB010101BBB",
        },
        {
            "entity_id": "C",
            "name": "Empresa Cobalto",
            "entity_type": "company",
            "rfc": "CCC010101CCC",
        },
        {
            "entity_id": "D",
            "name": "Empresa Delta",
            "entity_type": "company",
            "rfc": "DDD010101DDD",
        },
        {
            "entity_id": "E",
            "name": "Empresa Epsilon",
            "entity_type": "company",
            "rfc": "EEE010101EEE",
        },
        {
            "entity_id": "F",
            "name": "Empresa Faro",
            "entity_type": "company",
            "rfc": "FFF010101FFF",
        },
    ],
    "accounts": [],
    "transactions": [
        {
            "transaction_id": "T001",
            "timestamp": datetime(
                2026,
                9,
                10,
                9,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "A",
            "receiver_entity_id": "B",
            "amount": 100_000.0,
            "currency": "MXN",
            "description": "Payment A-B",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 1,
            },
        },
        {
            "transaction_id": "T002",
            "timestamp": datetime(
                2026,
                9,
                10,
                13,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "B",
            "receiver_entity_id": "C",
            "amount": 98_000.0,
            "currency": "MXN",
            "description": "Payment B-C",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 2,
            },
        },
        {
            "transaction_id": "T003",
            "timestamp": datetime(
                2026,
                9,
                10,
                18,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "C",
            "receiver_entity_id": "A",
            "amount": 97_000.0,
            "currency": "MXN",
            "description": "Payment C-A",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 3,
            },
        },
        {
            "transaction_id": "T004",
            "timestamp": datetime(
                2026,
                9,
                10,
                9,
                30,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "D",
            "receiver_entity_id": "B",
            "amount": 15_000.0,
            "currency": "MXN",
            "description": "Payment D-B",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 4,
            },
        },
        {
            "transaction_id": "T005",
            "timestamp": datetime(
                2026,
                9,
                10,
                10,
                15,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "E",
            "receiver_entity_id": "B",
            "amount": 20_000.0,
            "currency": "MXN",
            "description": "Payment E-B",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 5,
            },
        },
        {
            "transaction_id": "T006",
            "timestamp": datetime(
                2026,
                9,
                10,
                11,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "B",
            "receiver_entity_id": "D",
            "amount": 25_000.0,
            "currency": "MXN",
            "description": "Payment B-D",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 6,
            },
        },
        {
            "transaction_id": "T007",
            "timestamp": datetime(
                2026,
                9,
                10,
                12,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "B",
            "receiver_entity_id": "F",
            "amount": 30_000.0,
            "currency": "MXN",
            "description": "Payment B-F",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 7,
            },
        },
        {
            "transaction_id": "T008",
            "timestamp": datetime(
                2026,
                9,
                10,
                19,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "A",
            "receiver_entity_id": "B",
            "amount": 12_000.0,
            "currency": "MXN",
            "description": "Second payment A-B",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 8,
            },
        },
        {
            "transaction_id": "T009",
            "timestamp": datetime(
                2026,
                9,
                10,
                14,
                0,
                tzinfo=MX_TIMEZONE,
            ),
            "sender_entity_id": "F",
            "receiver_entity_id": "E",
            "amount": 7_500.0,
            "currency": "MXN",
            "description": "Payment F-E",
            "source_ref": {
                "file": "mock_transactions.csv",
                "row": 9,
            },
        },
    ],
}
